version: '3.1'
services:

  mysql:
    container_name: wypozyczalnia_db
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: zaq1@WSX
      MYSQL_DATABASE: WypozyczalniaAut
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: wypozyczalnia_phpmyadmin
    image: phpmyadmin:5.1
    ports:
      - 8081:80
    environment:
      - PMA_HOST=wypozyczalnia_db
      - PMA_PORT=3306

networks:
  default:
volumes:
  db:
